name: Update generated files
on:
  repository_dispatch:
    types: [models-update]

jobs:
  generate:
    name: generate files
    runs-on: ubuntu-latest
    steps:
    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.AUTOMATION_APP_ID }}
        private_key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Run go generate
      run: go generate ./...

    - name: Create or update PR
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ steps.generate-token.outputs.token }}
        commit-message: "update generated files"
        branch: update-generated-files
        delete-branch: true
        title: Update generated files
        body: "${{ github.event.client_payload.body }}"
        reviewers: ostcar
        assignees: ostcar
        milestone: 2
